version: '3'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres-db
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    networks:
      - my-network
    restart: always

  postgres-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - my-network
    restart: always
    
networks:
  my-network:
    driver: bridge